name: Development Pipeline

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint_test:
    needs: setup
    uses: ./.github/workflows/lint-test.yml

  unit_test:
    needs: setup
    uses: ./.github/workflows/unit-test.yml

  build:
    needs: [lint_test, unit_test]
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
