name: Development Pipeline

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint_test:
    needs: setup
    uses: ./.github/workflows/lint-check.yml

  unit_test:
    needs: setup
    uses: ./.github/workflows/unit-test.yml

  build:
    needs: [lint_test, unit_test]
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build application
        run: yarn build:docker
