name: Development Pipeline

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.event.repository.name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint_test:
    needs: setup
    uses: ./.github/workflows/lint-test.yml

  unit_test:
    needs: setup
    uses: ./.github/workflows/unit-test.yml

  build:
    needs: [lint_test, unit_test]
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ENV: ${{ secrets.DEV_ENV }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      HOST: ${{ secrets.HOST }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  notify:
    needs: deploy
    uses: ./.github/workflows/notify.yml
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
